/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package warkop;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel; 

/**
 *
 * @author piete
 */

public class WarkopCRUD extends javax.swing.JFrame {
    public Statement statement;
    public ResultSet result;
    public DefaultTableModel tableModel;
    Connection connect = koneksi.KoneksiWarkop.Koneksi();
    int total, hargaMakanan, hargaMinuman;
    
    /**
     * Creates new form WarkopCRUD
     */
    
public void transaksi() {
    Object[] transaksi = {
        "idtransaksi", "nama", "makanan", "hargamakanan", "minuman", "hargaminuman"
    };
    tableModel = new DefaultTableModel(null, transaksi);
    tablePesanan.setModel(tableModel);
}

public void tampilkan(){
    try {
            statement = connect.createStatement();
            tableModel.getDataVector().removeAllElements();
            tableModel.fireTableDataChanged();
            result = statement.executeQuery("SELECT * FROM transaksi");
            while (result.next()) {
                Object[] data = {
                    result.getString("idtransaksi"),
                    result.getString("nama"),
                    result.getString("makanan"),
                    result.getString("hargamakanan"),
                    result.getString("minuman"),
                    result.getString("hargaminuman"),
                };
                tableModel.addRow(data);
            }
        } catch(Exception e) {
            e.printStackTrace();
    }
}
    
public void kosongkan() {
    textID.setText("");
    inputNama.setText("");
    inputMakanan.setSelectedItem("");
    totalMakanan.setText("");
    inputMinuman.setSelectedItem("");
    totalMinuman.setText("");
}

public void harga(){
    inputMakanan.addActionListener(new ActionListener() {
        public void actionPerformed(ActionEvent a) {
            Object makanan = inputMakanan.getSelectedItem();
            try {
            if (makanan == "Indomie"){
                int hargaIndomie = 7000;
                totalMakanan.setText(Integer.toString(hargaIndomie));
            } else if (makanan == "Indomie Telor"){
                int hargaIntel = 9000;
                totalMakanan.setText(Integer.toString(hargaIntel));
            } else if (makanan == "Gorengan"){
                int hargaGorengan = 1000;
                totalMakanan.setText(Integer.toString(hargaGorengan));
            }
          } catch(Exception e){
                System.out.println(e.getMessage());
          }
        }
    });
    
    inputMinuman.addActionListener(new ActionListener() {
        public void actionPerformed(ActionEvent a) {
            Object minuman = inputMinuman.getSelectedItem();
            try {
                if (minuman == "Teh"){
                    int hargaTeh = 3000;
                    totalMinuman.setText(Integer.toString(hargaTeh));
                } else if (minuman == "Kopi"){
                    int hargaKopi = 3000;
                    totalMinuman.setText(Integer.toString(hargaKopi));
                } else if (minuman == "Susu"){
                    int hargaSusu = 4000;
                    totalMinuman.setText(Integer.toString(hargaSusu));
                }
            } catch(Exception e){
                System.out.println(e.getMessage());
            }
        }
    });
}

public void tampilID(String where) {
            try {
                statement = connect.createStatement();
                result = statement.executeQuery("SELECT * FROM transaksi " + where);

                while (result.next()) {
                    String id = result.getString("idtransaksi");
                    textID.setText(id);
                }
            } catch(Exception e){
                System.out.println(e.getMessage());
            }
        }

    public WarkopCRUD() {
        initComponents();
        transaksi();
        tampilkan();
        harga();
        buttonHapus.setEnabled(false);
        buttonUpdate.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        inputNama = new javax.swing.JTextField();
        textID = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablePesanan = new javax.swing.JTable();
        buttonSimpan = new javax.swing.JButton();
        buttonHapus = new javax.swing.JButton();
        buttonUpdate = new javax.swing.JButton();
        buttonReset = new javax.swing.JButton();
        inputMakanan = new javax.swing.JComboBox<>();
        inputMinuman = new javax.swing.JComboBox<>();
        totalMakanan = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        totalMinuman = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        buttonExit = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 0, 0));
        jLabel1.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("Warung Indomie");
        jLabel1.setOpaque(true);

        jLabel2.setText("ID");

        jLabel3.setText("Nama");

        jLabel4.setText("Makanan");

        jLabel5.setText("Minuman");

        inputNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNamaActionPerformed(evt);
            }
        });

        textID.setEditable(false);
        textID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textIDActionPerformed(evt);
            }
        });

        tablePesanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID Transaksi", "Nama", "Makanan", "Harga Makanan", "Minuman", "Harga Minuman"
            }
        ));
        tablePesanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePesananMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablePesanan);

        buttonSimpan.setText("Simpan");
        buttonSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSimpanActionPerformed(evt);
            }
        });

        buttonHapus.setText("Hapus");
        buttonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHapusActionPerformed(evt);
            }
        });

        buttonUpdate.setText("Update");
        buttonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUpdateActionPerformed(evt);
            }
        });

        buttonReset.setText("Reset");
        buttonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonResetActionPerformed(evt);
            }
        });

        inputMakanan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "pilih makanan", "Indomie", "Indomie Telor", "Gorengan" }));
        inputMakanan.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                inputMakananItemStateChanged(evt);
            }
        });
        inputMakanan.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                inputMakananInputMethodTextChanged(evt);
            }
        });
        inputMakanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputMakananActionPerformed(evt);
            }
        });
        inputMakanan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                inputMakananKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inputMakananKeyReleased(evt);
            }
        });

        inputMinuman.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "pilih minuman", "Teh", "Kopi", "Susu" }));
        inputMinuman.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                inputMinumanItemStateChanged(evt);
            }
        });
        inputMinuman.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                inputMinumanInputMethodTextChanged(evt);
            }
        });
        inputMinuman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputMinumanActionPerformed(evt);
            }
        });
        inputMinuman.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                inputMinumanKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inputMinumanKeyReleased(evt);
            }
        });

        totalMakanan.setEditable(false);
        totalMakanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalMakananActionPerformed(evt);
            }
        });

        jLabel6.setText("Harga Makanan");

        jLabel7.setText("Rp");

        totalMinuman.setEditable(false);
        totalMinuman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalMinumanActionPerformed(evt);
            }
        });

        jLabel8.setText("Rp");

        jLabel9.setText("Harga Minuman");

        buttonExit.setText("Exit");
        buttonExit.setIconTextGap(1);
        buttonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExitActionPerformed(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(255, 0, 0));
        jLabel10.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 255));
        jLabel10.setText("(Warmindo)");
        jLabel10.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(buttonSimpan)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonUpdate)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(buttonHapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonReset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(textID, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                        .addComponent(inputNama, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                        .addComponent(inputMakanan, 0, 166, Short.MAX_VALUE)
                        .addComponent(inputMinuman, 0, 166, Short.MAX_VALUE)
                        .addComponent(totalMakanan)
                        .addComponent(totalMinuman, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel10))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(textID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(inputNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(inputMakanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(inputMinuman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(totalMakanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(totalMinuman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonSimpan)
                            .addComponent(buttonUpdate)
                            .addComponent(buttonHapus)
                            .addComponent(buttonReset)
                            .addComponent(buttonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26))
        );

        setSize(new java.awt.Dimension(895, 342));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSimpanActionPerformed
        try {
            String query = "INSERT INTO transaksi VALUES (NULL, '" + inputNama.getText() + "', '" 
            + inputMakanan.getSelectedItem() + "', '"
            + totalMakanan.getText() + "', '"
            + inputMinuman.getSelectedItem() + "', '"
            + totalMinuman.getText() + "')";
            statement = connect.createStatement();
            statement.executeUpdate(query);

            kosongkan();
            tampilkan();
            JOptionPane.showMessageDialog(null, "Simpan berhasil!");
        } catch(Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_buttonSimpanActionPerformed

    private void tablePesananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePesananMouseClicked
        textID.setText(tablePesanan.getValueAt(tablePesanan.getSelectedRow(), 0).toString());
        inputNama.setText(tablePesanan.getValueAt(tablePesanan.getSelectedRow(), 1).toString());
        inputMakanan.setSelectedItem(tablePesanan.getValueAt(tablePesanan.getSelectedRow(), 2).toString());
        totalMakanan.setText(tablePesanan.getValueAt(tablePesanan.getSelectedRow(), 3).toString());
        inputMinuman.setSelectedItem(tablePesanan.getValueAt(tablePesanan.getSelectedRow(), 4).toString());
        totalMinuman.setText(tablePesanan.getValueAt(tablePesanan.getSelectedRow(), 5).toString());
        
        buttonSimpan.setEnabled(false);
        buttonUpdate.setEnabled(true);
        buttonHapus.setEnabled(true);
    }//GEN-LAST:event_tablePesananMouseClicked
     
    private void buttonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonResetActionPerformed
        kosongkan();
    }//GEN-LAST:event_buttonResetActionPerformed

    private void buttonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUpdateActionPerformed
        try{
            String query = "UPDATE transaksi SET nama = '" + inputNama.getText() + "',"
                + "makanan = '" + inputMakanan.getSelectedItem() + "', "
                + "hargamakanan = '" + totalMakanan.getText() + "', "
                + "minuman = '" + inputMinuman.getSelectedItem() + "', "
                + "hargaminuman = '" + totalMinuman.getText() +  "'" 
                + "WHERE idtransaksi = '" + textID.getText() + "'";
            statement = connect.createStatement();
            statement.executeUpdate(query);
            
            kosongkan();
            tampilkan();
            tampilID("");
            JOptionPane.showMessageDialog(null, "Update berhasil!");
        } catch(Exception e){
            System.out.println(e.getMessage());
        }
        buttonSimpan.setEnabled(true);
        buttonUpdate.setEnabled(false);
        buttonHapus.setEnabled(false);
    }//GEN-LAST:event_buttonUpdateActionPerformed

    private void buttonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHapusActionPerformed
        try{
            String query = "DELETE FROM transaksi WHERE idtransaksi = '" + textID.getText() + "'";
            statement = connect.createStatement();
            statement.executeUpdate(query);
            
            kosongkan();
            tampilkan();
            tampilID("");
            JOptionPane.showMessageDialog(null, "Hapus berhasil!");
        } catch(Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_buttonHapusActionPerformed

    private void inputMakananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputMakananActionPerformed
        
    }//GEN-LAST:event_inputMakananActionPerformed

    private void textIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textIDActionPerformed
        
    }//GEN-LAST:event_textIDActionPerformed

    private void inputNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNamaActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        buttonSimpan.setEnabled(true);
        buttonUpdate.setEnabled(false);
        buttonHapus.setEnabled(false);
    }//GEN-LAST:event_formMouseClicked

    private void inputMinumanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputMinumanActionPerformed
        
    }//GEN-LAST:event_inputMinumanActionPerformed

    private void totalMakananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalMakananActionPerformed
        
    }//GEN-LAST:event_totalMakananActionPerformed

    private void inputMakananItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_inputMakananItemStateChanged
        
    }//GEN-LAST:event_inputMakananItemStateChanged

    private void inputMakananKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputMakananKeyReleased
        
    }//GEN-LAST:event_inputMakananKeyReleased

    private void inputMinumanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputMinumanKeyReleased
        
    }//GEN-LAST:event_inputMinumanKeyReleased

    private void inputMinumanItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_inputMinumanItemStateChanged
      
    }//GEN-LAST:event_inputMinumanItemStateChanged

    private void inputMakananKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputMakananKeyPressed
              
    }//GEN-LAST:event_inputMakananKeyPressed

    private void inputMakananInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_inputMakananInputMethodTextChanged
        
    }//GEN-LAST:event_inputMakananInputMethodTextChanged

    private void inputMinumanInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_inputMinumanInputMethodTextChanged
        
    }//GEN-LAST:event_inputMinumanInputMethodTextChanged

    private void inputMinumanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputMinumanKeyPressed
        
    }//GEN-LAST:event_inputMinumanKeyPressed

    private void totalMinumanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalMinumanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalMinumanActionPerformed

    private void buttonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExitActionPerformed
        int dialog = JOptionPane.showOptionDialog(this, "Anda ingin kembali ke menu awal?", null,
            JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);

        if(dialog == JOptionPane.YES_OPTION){
            setVisible(false);
            new LoginWarkop().setVisible(true);
        }
    }//GEN-LAST:event_buttonExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WarkopCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WarkopCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WarkopCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WarkopCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WarkopCRUD().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonExit;
    private javax.swing.JButton buttonHapus;
    private javax.swing.JButton buttonReset;
    private javax.swing.JButton buttonSimpan;
    private javax.swing.JButton buttonUpdate;
    private javax.swing.JComboBox<String> inputMakanan;
    private javax.swing.JComboBox<String> inputMinuman;
    private javax.swing.JTextField inputNama;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablePesanan;
    private javax.swing.JTextField textID;
    private javax.swing.JTextField totalMakanan;
    private javax.swing.JTextField totalMinuman;
    // End of variables declaration//GEN-END:variables
}
